version: '3'

includes:
  battery:
    taskfile: battery/Taskfile.yml
    dir: battery

  fuzzytime:
    taskfile: fuzzytime/Taskfile.yml
    dir: fuzzytime

  mem:
    taskfile: mem/Taskfile.yml
    dir: mem

  time:
    taskfile: time/Taskfile.yml
    dir: time

tasks:
  plugins:
      cmds:
        - task: battery:default
        - task: fuzzytime:default
        - task: mem:default
        - task: time:default
