version: '3'

includes:
  battery:
    taskfile: battery/Taskfile.yml
    dir: battery

  cpu:
    taskfile: cpu/Taskfile.yml
    dir: cpu

  fuzzytime:
    taskfile: fuzzytime/Taskfile.yml
    dir: fuzzytime

  mem:
    taskfile: mem/Taskfile.yml
    dir: mem

  time:
    taskfile: time/Taskfile.yml
    dir: time

  uptime:
    taskfile: uptime/Taskfile.yml
    dir: uptime

  weather:
    taskfile: weather/Taskfile.yml
    dir: weather


tasks:
  sizes:
    cmds:
      - du -shc **/*.wasm

  plugins:
      cmds:
        - task: battery:default
        - task: cpu:default
        - task: fuzzytime:default
        - task: mem:default
        - task: time:default
        - task: uptime:default
        - task: weather:default
