version: '3'

vars:
  BINARY: 'cpu'
  DISTPATH: 'dist-newstyle/**/build/cpu'

env:
  GHC_WASM_PATH: '{{.HOME}}/.ghc-wasm'
  GHC_CABAL_PATH: '{{.GHC_WASM_PATH}}/wasm32-wasi-cabal'

tasks:
  build:
    cmds:
      - |
        {{.GHC_CABAL_PATH}}/bin/wasm32-wasi-cabal build

  optimize:
    cmds:
      - wasm-opt -Os {{.DISTPATH}}/{{.BINARY}}.wasm --output ./{{.BINARY}}.wasm

  strip:
    cmds:
      - wasm-strip ./{{.BINARY}}.wasm

  run:
    cmds:
      - extism call --wasi ./{{.BINARY}}.wasm run

  install:
    cmds:
      - curl https://gitlab.haskell.org/haskell-wasm/ghc-wasm-meta/-/raw/master/bootstrap.sh | sh

  default:
    cmds:
      - task: build
      - task: optimize
      - task: strip
